# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.disksize.size = "100GB"
  config.vm.synced_folder "exchange/", "/home/vagrant/exchange"  
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
	vb.cpus = 2
  end

end
